FROM python:3.10

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir Flask
RUN pip install pymongo
RUN pip install countryinfo
RUN pip install geopy
RUN pip install pika
RUN pip install requests

ENV PYTHONUNBUFFERED=1

EXPOSE 8001

CMD sleep 10; python init_airline1_db.py