apiVersion: apps/v1
kind: Deployment
metadata:
  name: airline-interaction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airline-interaction
  template:
    metadata:
      labels:
        app: airline-interaction
    spec:
      containers:
        - name: airline-interaction
          image: navjots20/broker:latest
          ports:
            - containerPort: 8021
          env:
            - name: MONGO_HOST
              value: mongo-cluster-ip-service
            - name: MONGO_PORT
              value: "27017"
            - name: JWT_SECRET
              value: "123TEST"
---
apiVersion: v1
kind: Service
metadata:
  name: broker-srv
spec:
  selector:
    app: airline-interaction
  ports:
    - name: broker
      port: 8021
      targetPort: 8021
      protocol: TCP