apiVersion: batch/v1
kind: Job
metadata:
  name: init-airline1-db
spec:
  template:
    spec:
      containers:
      - name: init-airline1-db
        image: jettzgg/init-airline1-db
        command: ["python", "/app/init_airline1_db.py"]
      restartPolicy: Never
