apiVersion: batch/v1
kind: Job
metadata:
  name: init-airline2-db
spec:
  template:
    spec:
      containers:
      - name: init-airline2-db
        image: jettzgg/init-airline2-db
        command: ["python", "/app/init_airline2_db.py"]
      restartPolicy: Never
