version: '3'

services:
  spring-boot-app:
    container_name: broker
    image: broker
    ports:
      - "8021:8021"
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.10-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
